Add Stale issue workflow
Flow-Launcher/Flow.Launcher pull request #1104
Opened 2022-03-29 12:04 UTC by Garulf

With this workflow Issues and PRs that have not received any updates will be marked with a `stale` label. 

Any Issues will be closed after 5 days if they are not updated after being marked. 
PRs will never be closed.
Any PR that has a milestone will be exempt from the stale label.

2022-03-29 21:49 UTC, deefrawley commented
For issues that are waiting for a release to fix, where the release is taking longer than thirty days, is the idea to add an update comment or remove the label to keep it open and waiting?

2022-04-19 03:20 UTC, Garulf commented
That's how it would work I guess.

2022-04-19 08:56 UTC, jjw24 requested changes
We would have issues that are waiting to be fixed, yet to be fixed or  lower priority, would it be better to implement closing based on a label i.e. 'waiting for response'?

Also don't close PRs regardless of how inactive they are, because the team might not get around to them or they need further implementation.

2022-04-19 17:18 UTC, Garulf commented
> We would have issues that are need investigation, waiting to be fixed, yet to be fixed or acknowledged but lower priority, would it be better to implement closing based on a label i.e. 'waiting for response'? So we would mark stale the ones that have been waiting from user response > 5 days and close after 15 days. All other issues still open will mean they are of the four mentioned status.
> 
That could work, but I feel if we haven't responded in the current cut off period (30 + 5 days) it's probably not being responded to because it is just a stale issue. 

Also marking an issue as stale isn't necessarily a bad thing. It could help draw attention to issues that may have fallen through the cracks. 
> 
> Also don't close PRs regardless of how inactive they are, because the team might not get around to them or they need further implementation.

Current settings only mark PRs with a "Stale" label unless they're included in a milestone. Never are they closed. Hopefully this can give a kick start to some PRs that have been sitting and help indicate what's been sitting around for an extended period and may need some attention.

2022-04-20 07:45 UTC, jjw24 commented
Yeah ok. I personally keep open only issues that need work on and strive to maintain a low count, but we can give this a try too.

2022-04-20 07:46 UTC, jjw24 approved these changes

2022-04-20 07:47 UTC, merged