Support QTTabBar
Flow-Launcher/Flow.Launcher pull request #2803
Opened 2024-06-25 07:40 UTC by onesounds

## What's the PR
- Support for opening tab in exist window when using qttabbar.

## Detail 
- Added a QtTabBar in "File Manager" entry. 
- For new installations, the qttabbar setting is listed.
- Existing users are not listing. but if user add and select "qttabbar" (in name. case-insensitive), it will behave as a qttabbar.

## Test Cases
- [x] opening in tabs in qttabbar.
- [x] Doesn't affect existing user settings.

2024-06-25 08:05 UTC, onesounds commented on Flow.Launcher/PublicAPIInstance.cs
> +            var customExplorerList = _settingsVM.Settings.CustomExplorerList;
OK.

2024-06-25 12:46 UTC, jjw24 commented on Flow.Launcher/PublicAPIInstance.cs
> -            explorer.Start();
Does this existing process start logic not work for QTTabBar setup?

2024-06-26 10:38 UTC, jjw24 requested changes
We need to handle the scenario where the new OTTabBar entry should show up on existing user data, because the way the code loads the existing user settings it won't load the new entry in unless it's a fresh install.

2024-06-26 14:53 UTC, onesounds commented
> We need to handle the scenario where the new OTTabBar entry should show up on existing user data, because the way the code loads the existing user settings it won't load the new entry in unless it's a fresh install.

I agree, but I don't know how to do it. I considered adding a separate setting for this item for existing user, but there was no proper location. (And since qtttabbar is not being maintained. so I didn't want to add a setting menu for this.)

Let me ask chatgpt...

2024-06-26 15:29 UTC, onesounds commented
> We need to handle the scenario where the new OTTabBar entry should show up on existing user data, because the way the code loads the existing user settings it won't load the new entry in unless it's a fresh install. In this case, the qttabbar is an item that cannot be deleted.

Now, there are three ways to support this. I can work with 1 or 2. 
1. Each time the user launches, we check the user's settings to see if the "qttabbar" entry exists, and if not, we add it to the list.

2. Add qttabbar and explorer as user-immutable constant entries and adjust the list.
In this case, we either have to risk messing with existing users' FileManager settings(settings.CustomExplorerIndex), or we have to reset it and change it to store and recognize by "name" (string). Also, in this case, qttabbar, which should be lower in the support list, is occupying the second list.

3.If the user doesn't have qttabbar setting, it should be added automatically, and if it is already added, it should not be added again if the user subsequently deletes it.  I don't think I can do this, and while it's probably possible, it results in an incredibly complex structure. Is there any other easy way to do this? 

This is entirely down to me structuring it incorrectly at the beginning, However, I don't know if it's worth adding such a structure for this utility. Given the importance of qttabbar support, I think my PR state is good enough. I can't do 3.  After reviewing all 3, I still think what I proposed is the right way to go, but if you want to do 1 and 2 to add a qttabbar item to the list that almost all existing users will never use, that's fine. Just pick one and let me know.

2024-06-27 00:54 UTC, onesounds commented
I'm closing that PR because I don't think my plan is clear and it's causing confusion. If I come up with a new idea, I'll write a new one, or others can make one.

2024-07-01 11:08 UTC, jjw24 commented
> I'm closing that PR because I don't think my plan is clear and it's causing confusion. If I come up with a new idea, I'll write a new one, or others can make one.

Thanks for helping to investigate how to get QTTabBar integrated. We just need to do a slight tweaking that will have less complexity, please see my commit. The commit will allow QTTabBar be added as a custom profile, which means there is no need to provide backwards support for a new default profile. We can add it like this:


![image](https://github.com/Flow-Launcher/Flow.Launcher/assets/26427004/97e7f758-8835-433e-bbae-c05b5309e703)

2024-07-01 11:09 UTC, jjw24 commented
@onesounds could you please help make the change to allow the 'Arg For Folder' and 'Arg For File' fields to be blank.

2024-07-02 02:14 UTC, onesounds commented
> 'Arg For Folder' and 'Arg For File'

@jjw24 Done.

2024-07-07 07:56 UTC, jjw24 approved these changes

2024-07-07 08:01 UTC, merged