Global hotkey refactor
Flow-Launcher/Flow.Launcher pull request #834
Opened 2021-11-27 20:27 UTC by taooceros

fix #788

2021-11-29 09:05 UTC, jjw24 commented
@taooceros fair bit of method signature changes. can you give me a quick overview of why they are changed please

2021-12-04 00:01 UTC, taooceros commented
> @taooceros fair bit of method signature changes. can you give me a quick overview of why they are changed please

Only the global hotkey event in publicapi is obsolete, and two new api is added to handle the same work.

2021-12-04 08:06 UTC, taooceros commented
Unsafe is used because
1. It's reasonable to have high performance here because every key hit will trigger the running of the function once.
2. I would like to try the new function pointer feature🤔😂
3. I am not sure whether some issues may exist because of unsafe, so we should take a small set of testing here. However, it is unlikely we need to unload assembly for infrastructure, so it should be fine.

2021-12-05 23:38 UTC, onesounds submitted a review, later dismissed

2021-12-05 23:48 UTC, Garulf approved these changes

2021-12-06 09:29 UTC, jjw24 commented on Plugins/Flow.Launcher.Plugin.Shell/Main.cs
> -            mainWindow.Focus();
does this still need focus applied?

2021-12-06 09:40 UTC, jjw24 commented on Flow.Launcher.Infrastructure/Hotkey/GlobalHotkey.cs
> +            return (IntPtr)(-1);
what's this change?

2021-12-06 09:41 UTC, jjw24 commented
what's been tested with this change so far?

also need to bump Shell plugin

2021-12-06 09:46 UTC, onesounds commented
> what's been tested with this change so far?
> 
> also need to bump Shell plugin

It is a pr to solve the problem that when win+r is pressed, the flow closes and the run command (win+r by os) operates. I understand that the code has become complicated because there is a part in the middle of the work that does not work properly related to animation.

2021-12-06 09:53 UTC, jjw24 commented
well i dont exactly understand this change, so if @taooceros is sure this is good to go and not going to break anything then happy for one of you to approve and merge this.

2021-12-06 18:35 UTC, taooceros commented
> well i dont exactly understand this change, so if @taooceros is sure this is good to go and not going to break anything then happy for one of you to approve and merge this.

The main change is because the multicast delegate (event) fails to return all return values so that the win+r may not work with the presence of the windows walker. The main change of the pull request change the event to a list of Func to retrieve the return value correctly.
Also, because c# 9 added the function pointer, so I think it's cool to use that in the hook for better performance because the hook is fired in every single keyboard click.

2021-12-07 02:04 UTC, jjw24 requested changes
somehow the artifacts are smaller, doesnt seem normal.

![image](https://user-images.githubusercontent.com/26427004/144952663-93eef5ba-5368-4566-a97f-e570d4d8bc98.png)

2021-12-08 05:54 UTC, Garulf commented
- Build looks good
- <kbd>Win</kbd>+<kbd>R,/kbd> fixed
- Fix for Tab complete
- Working with Window Walker
- No crashes

Good to go?

2021-12-08 09:55 UTC, jjw24 approved these changes
unsure of code changes but tested working fine, will merge since this addresses an issue in current dev

2021-12-08 09:56 UTC, merged